"""empty message

Revision ID: 067f3bc9689e
Revises: 2c82530671c0
Create Date: 2023-04-28 13:29:43.962066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067f3bc9689e'
down_revision = '2c82530671c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.alter_column('public_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.alter_column('public_key',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
