"""empty message

Revision ID: 2c82530671c0
Revises: aa13be6848cf
Create Date: 2023-04-28 12:34:20.876087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c82530671c0'
down_revision = 'aa13be6848cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegatee_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('re_key', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('path', sa.String(length=256), nullable=False))
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('public_key', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('private_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('private_key')
        batch_op.drop_column('public_key')
        batch_op.drop_column('name')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('path')
        batch_op.drop_column('name')
        batch_op.drop_column('type')

    op.drop_table('share')
    op.drop_table('log')
    # ### end Alembic commands ###
