"""empty message

Revision ID: 56db3cc1c79b
Revises: 72cf43886c8b
Create Date: 2023-05-02 17:16:06.676850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56db3cc1c79b'
down_revision = '72cf43886c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('public_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('private_key', sa.LargeBinary(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['public_key'])
        batch_op.create_unique_constraint(None, ['private_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('private_key')
        batch_op.drop_column('public_key')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
