name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt
    - run: terraform init
    - run: terraform apply

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - run: pip install -r requirements.txt
    - run: gcloud auth activate-service-account --key-file=key.json
    - run: gcloud builds submit --config cloudbuild.yaml