name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the Docker image
        run: docker build -t my-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/terraform@v1.1.4

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply

      - name: Deploy to Kubernetes
        run: gcloud container clusters get-credentials my-cluster
        run: kubectl apply -f deployment.yaml